# Generated by Django 5.2.4 on 2025-07-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('Only Me', 'Only Me')], default='Public', max_length=10),
        ),
    ]
