# Generated by Django 5.2.4 on 2025-07-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
