# Generated by Django 5.0.7 on 2025-08-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_customuser_date_of_birth_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
