# Generated by Django 5.2.4 on 2025-07-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_customuser_bio_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
